package com.probase.nrfa.enumerations;

public enum RequestType {
	NEW_USER_CREATION, USER_ACCOUNT_UPDATE, DEBIT_CARD, CREDIT_CARD, 
	NEW_CARD_CREATION, CARD_UPDATE, CARD_ASSIGN_TO_DISTRIBUTOR, 
	CARD_ASSIGN_TO_CUSTOMER, CARD_ASSIGN_UNIQUE_ID, NEW_DISTRIBUTOR_CREATION, 
	UPDATE_DISTRIBUTOR, LOGIN_USER, LOGIN_USER_OTP, LOGOUT_USER, FORGOT_PASSWORD, 
	CHANGE_USER_PASSWORD, DISTRIBUTOR_VIRTUAL_ACCOUNT_CREATION, CREDIT_DISTRIBUTOR_ACCOUNT,
	UPDATE_DISTRIBUTOR_ACCOUNT_BALANCE, NEW_CUSTOMER_CREATION, UPDATE_CUSTOMER_DETAILS, NEW_MERCHANT_CREATION, UPDATE_MERCHANT, 
	NEW_MERCHANT_SCHEME, NEW_TRAFFIC_TOLL_PRICE, UPDATE_TRAFFIC_TOLL_PRICE, NEW_TRAFFIC_SCHEME, NEW_TRAFFIC_TOLL_ROUTE_LANE, 
	NEW_TRAFFIC_TOLL_ROUTE, TRANSACTION_REVERSAL_ACTION, TRANSACTION_REVERSAL_REQUEST, DEPOSIT_CASH_DISTRIBUTOR_ACCOUNT, 
	DEPOSIT_CASH_GENERAL_POOL_ACCOUNT, CARD_DEBIT_AT_TOLL, CARD_BALANCE_UPDATE, CASH_COLLECT_AT_TOLL, CUSTOMER_LOAD_CARD_VIA_DISTRIBUTOR_ONUS, 
	CUSTOMER_LOAD_CARD_VIA_DISTRIBUTOR_NOTONUS, CUSTOMER_DEPOSIT_CASH_VIA_MERCHANT_OTC_ONUS, CUSTOMER_DEPOSIT_CASH_VIA_MERCHANT_OTC_NOTONUS, 
	NEW_DEVICE_CREATION, SYNC_TO_DEVICE, NEW_BANK_CREATION, ASSIGN_TOLL_USER_A_ROUTE, ASSIGN_TOLL_USER_NO_ROUTE, CARD_SMS_ACTIVATE
	
}
